# Generated by Django 4.2.4 on 2023-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('idTutor', models.AutoField(primary_key=True, serialize=False)),
                ('numeroEmpleado', models.CharField(max_length=7, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('apellidoMaterno', models.CharField(max_length=45)),
                ('cubiculo', models.CharField(default=None, max_length=20)),
                ('telefono', models.CharField(default=None, max_length=10)),
            ],
        ),
    ]
