# Generated by Django 4.2.4 on 2023-08-07 19:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_tutor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorado',
            fields=[
                ('idTutorado', models.IntegerField(primary_key=True, serialize=False)),
                ('boletaTutorado', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=45)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('apellidoMaterno', models.CharField(max_length=45)),
                ('semestre', models.CharField(default=None, max_length=15)),
                ('telefono', models.CharField(default=None, max_length=45)),
                ('numTutoresAsignados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='TutoriaIndividual',
            fields=[
                ('idTutoriaIndividual', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombreTutoriaIndividual', models.CharField(max_length=45)),
                ('idTutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutor')),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutorado')),
            ],
        ),
    ]
