# Generated by Django 4.2.4 on 2023-08-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_tutorado_tutoriaindividual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorado',
            name='idTutorado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
