# Generated by Django 4.2.4 on 2023-08-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_tutorado_idtutorado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorado',
            name='telefono',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
