# Generated by Django 4.2.4 on 2023-08-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_bitacoraindividualtutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraindividualtutor',
            name='idTutor',
            field=models.IntegerField(default=None),
        ),
    ]
