# Generated by Django 4.2.4 on 2023-08-11 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_bitacoraindividualtutor_idtutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoraindividualtutor',
            name='idTutor',
        ),
        migrations.CreateModel(
            name='NotasIndividualesTutorado',
            fields=[
                ('idNotasIndividualesTutorado', models.AutoField(primary_key=True, serialize=False)),
                ('idTutorado', models.IntegerField(default=None)),
                ('nota', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idTutoriaIndividual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriaindividual')),
            ],
        ),
    ]
