# Generated by Django 4.2.4 on 2023-08-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_remove_bitacoraindividualtutor_idtutor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasindividualestutorado',
            name='idTutorado',
        ),
    ]
