# Generated by Django 4.2.4 on 2023-08-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_remove_notasindividualestutorado_idtutorado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoriaGrupal',
            fields=[
                ('idTutoriaGrupal', models.AutoField(primary_key=True, serialize=False)),
                ('nombreGrupo', models.CharField(default=None, max_length=45)),
                ('cupoDisponible', models.IntegerField(default=45)),
                ('salon', models.CharField(default=None, max_length=20)),
                ('idTutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='ListaTutoriaGrupal',
            fields=[
                ('idListaTutoriaGrupal', models.AutoField(primary_key=True, serialize=False)),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutorado')),
                ('idTutoriaGrupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriagrupal')),
            ],
        ),
    ]
