# Generated by Django 4.2.4 on 2023-08-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_tutoriagrupal_listatutoriagrupal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraGrupalTutor',
            fields=[
                ('idBitacoraGrupalTutor', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idTutoriaGrupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriagrupal')),
            ],
        ),
        migrations.CreateModel(
            name='AnunciosGrupalesTutor',
            fields=[
                ('idAnunciosGrupalesTutor', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idTutoriaGrupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriagrupal')),
            ],
        ),
    ]
