# Generated by Django 4.2.4 on 2023-09-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_bitacoragrupaltutor_anunciosgrupalestutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoconferenciasIndividuales',
            fields=[
                ('idVideoconferenciaIndivual', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('start_url', models.URLField(default=None, max_length=500)),
                ('join_url', models.URLField(default=None)),
                ('meeting_code', models.CharField(default=None, max_length=30)),
                ('meeting_password', models.CharField(default=None, max_length=30)),
                ('idTutoriaIndividual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriaindividual')),
            ],
        ),
        migrations.CreateModel(
            name='VideoconferenciasGrupales',
            fields=[
                ('idVideoconferenciaGrupal', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('start_url', models.URLField(default=None, max_length=500)),
                ('join_url', models.URLField(default=None)),
                ('meeting_code', models.CharField(default=None, max_length=30)),
                ('meeting_password', models.CharField(default=None, max_length=30)),
                ('idTutoriaGrupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriagrupal')),
            ],
        ),
    ]
