# Generated by Django 4.2.4 on 2023-11-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_videoconferenciasindividuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriagrupal',
            name='passwordGrupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
