# Generated by Django 4.2.4 on 2023-09-04 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoconferenciasGrupales',
            fields=[
                ('idVideoconferenciaGrupal', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField()),
                ('idTutoriaGrupal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriagrupal')),
            ],
        ),
        migrations.CreateModel(
            name='VideoconferenciasIndividuales',
            fields=[
                ('idVideoconferenciaIndivual', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=80)),
                ('start_time', models.DateTimeField()),
                ('idTutoriaIndividual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutoriaindividual')),
            ],
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
