# Generated by Django 4.2.4 on 2023-09-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0014_videoconferenciasindividuales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoconferenciasgrupales',
            name='start_url',
        ),
        migrations.RemoveField(
            model_name='videoconferenciasindividuales',
            name='start_url',
        ),
    ]
