# Generated by Django 4.2.4 on 2023-11-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_tutoriagrupal_passwordgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='zoomUserID',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
