# Generated by Django 4.2.4 on 2023-09-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0015_videoconferenciasgrupales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconferenciasgrupales',
            name='meeting_code',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='videoconferenciasgrupales',
            name='meeting_password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='videoconferenciasgrupales',
            name='personal_meeting_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='videoconferenciasindividuales',
            name='meeting_code',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='videoconferenciasindividuales',
            name='meeting_password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='videoconferenciasindividuales',
            name='personal_meeting_url',
            field=models.URLField(default=None),
        ),
    ]
