# Generated by Django 4.2.4 on 2023-09-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_videoconferenciasgrupales_meeting_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoconferenciasgrupales',
            old_name='personal_meeting_url',
            new_name='join_url',
        ),
        migrations.RenameField(
            model_name='videoconferenciasindividuales',
            old_name='personal_meeting_url',
            new_name='join_url',
        ),
        migrations.AddField(
            model_name='videoconferenciasgrupales',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='videoconferenciasgrupales',
            name='start_url',
            field=models.URLField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='videoconferenciasindividuales',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='videoconferenciasindividuales',
            name='start_url',
            field=models.URLField(default=None, max_length=300),
        ),
    ]
