# Generated by Django 4.2.4 on 2023-11-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0016_tutor_zoomuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='zoomUserID',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
