# Generated by Django 4.2.4 on 2023-12-04 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_alter_tutor_zoomuserid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('idChat', models.AutoField(primary_key=True, serialize=False)),
                ('idTutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutor')),
                ('idTutorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.tutorado')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('idChat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.chat')),
            ],
        ),
    ]
