# Generated by Django 4.2.4 on 2023-09-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0017_rename_personal_meeting_url_videoconferenciasgrupales_join_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoconferenciasgrupales',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='videoconferenciasindividuales',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
