# Generated by Django 4.2.4 on 2023-12-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0019_mensaje_tutorenvia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorado',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
    ]
