# Generated by Django 4.2.4 on 2023-12-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0022_alter_tutor_cubiculo_alter_tutoriagrupal_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorado',
            name='genero',
            field=models.CharField(default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='tutorado',
            name='semestre',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
