# Generated by Django 4.2.4 on 2023-12-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0026_chat_mensajes_no_leidos_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='acepta_privacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorado',
            name='acepta_privacidad',
            field=models.BooleanField(default=False),
        ),
    ]
