# Generated by Django 4.2.4 on 2023-12-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0027_tutor_acepta_privacidad_tutorado_acepta_privacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraindividualtutor',
            name='areasIntervencion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
