# Generated by Django 4.2.4 on 2023-12-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0028_bitacoraindividualtutor_areasintervencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraindividualtutor',
            name='areasIntervencion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
