# Generated by Django 4.2.4 on 2023-12-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0029_alter_bitacoraindividualtutor_areasintervencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoragrupaltutor',
            name='areasIntervencion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
