# Generated by Django 4.2.4 on 2023-12-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0031_rename_areasintervencion_bitacoragrupaltutor_intervencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciosgrupalestutor',
            name='nota',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bitacoragrupaltutor',
            name='nota',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bitacoraindividualtutor',
            name='nota',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notasindividualestutorado',
            name='nota',
            field=models.CharField(max_length=1000),
        ),
    ]
